# client-a.yaml
apiVersion: v1
kind: Service
metadata:
  name: client-a
spec:
  selector:
    app: client-a
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-a
  template:
    metadata:
      labels:
        app: client-a
    spec:
      containers:
        - name: client-a
          image: client-a:latest
          imagePullPolicy: IfNotPresent  # Use for local images
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: TARGET_PORT
              value: "8080"